# About BioSUPERCAP 

## Aim  
The BioSUPERCAP project aims to create innovative energy storage devices that harness the natural capabilities of electroactive bacteria.


## Overview 
Energy conversion and storage technologies based on renewable non-fossil fuel resources are urgently needed for the human and environment well-being. 
Microorganisms, able to transform the chemical energy stored in organic matter into electrical power, are considered as an alternative to the conventional solar and wind renewable energy sources. 

This project will employ living electroactive bacteria for the development of a new class energy storage devices, i.e. self-charging biosupercapacitors. 

The research work will be led by Dr. Christos Trapalis (Principal Investigator) from the National Centre for Scientific Research “Demokritos” in close corroboration with Dr. Dionissios Sgouras from the Hellenic Pasteur Institute. Their research groups have high expertize in the field of material science/supercapacitors and microbiology, respectively.


## Duration
**36 months**


<!-- rebuild -->
