<style>
h2 {
  border-bottom: none !important;
}
</style>


# PI and Team





## Principal Investigator:
### Dr. CHRISTOS TRAPALIS

*Director of Research, Head of Nanofunctional and Nanocomposite Materials Laboratory* 

Dr. C. Trapalis is a Chemical Engineer with scientific expertize in the field of nanoscience and nanotechnology, carbon based materials, functionalized graphene and graphene oxide, 2D heterostructures, nanostructured powders and coatings, visible light active photocatalysts for NOx removal, water splitting, solar fuels, CO2 to nanocarbons conversion and hybrid organic–inorganic materials.

*e-mail:* [c.trapalis@inn.demokritos.gr ](mailto:c.trapalis@inn.demokritos.gr?subject=BioSUPERCAP%20Inquiry)

*Personal links:*

[INN-Demokritos](https://inn.demokritos.gr/person/christos-trapalis/)

[Google Scholar profile](https://scholar.google.com/citations?hl=en&user=1sxqxO4AAAAJ&view_op=list_works&sortby=pubdate)

*Other projects links:*

[2D-photodomi project](https://www.2dphotodomi.com)

[Carbongreen project](https://www.carbongreenproject.com/about-carbongreen)

[Apogeion project](https://www.apogeionproject.com)


<div style="margin-bottom: 2rem;"></div>

<div style="margin-bottom: 2rem;"></div>




## Team: 

<div style="margin-bottom: 2rem;"></div>

### Dr. DIONYSSIOS SGOYRAS

*Director of Research Director, Head of Laboratory of Medical Microbiology at Hellenic Pasteur Institute*

Dr. D. Sgouras is a Chemist. His research interests are focused on bacterial pathogenesis and most specifically, Helicobacter pylori virulence factors and their effect on host intracellular signaling pathways, focusing mainly on epithelial cell pathogenesis and tissue remodeling during the infection. 

*e-mail:* [sgouras@pasteur.gr](mailto:sgouras@pasteur.gr?subject=BioSUPERCAP%20Inquiry)  

<div style="margin-bottom: 2rem;"></div>

<div style="margin-bottom: 2rem;"></div>



### Dr. NADIA TODOROVA

*Research Scientist in the Institute of Nanoscience and Nanotechnologies, NCSR "Demokritos"* 

Dr. N. Todorova is a Chemical Engineer. Her research is focused on synthesis and characterization of functional 2D carbon-based materials (Graphene, MXenes, g-C3N4) and heterostructures, development of semiconductor photocatalysts for environmental (NOx removal, H2 production, CO2 reduction) and antibacterial applications.

*e-mail:* [n.todorova@inn.demokritos.gr](mailto:n.todorovas@inn.demokritos.gr?subject=BioSUPERCAP%20Inquiry)

<div style="margin-bottom: 2rem;"></div>

<div style="margin-bottom: 2rem;"></div>



### Dr. BEATRIZ MARTINEZ-GONZALEZ

*Research Scientist at Hellenic Pasteur Institute*

Dr. Beatriz Martinez-Gonzalez is a Pharmacist. Her work focuses on Helicobacter pylori infection, including studies of antimicrobial resistance, bacterial pathogenesis, and the effectiveness of eradication regimens. Her research also encompasses molecular microbiology and clinical surveillance related to gastrointestinal infectious diseases. 

*e-mail:* [bmartinez@pasteur.gr](mailto:bmartinez@pasteur.gr?subject=BioSUPERCAP%20Inquiry)

<div style="margin-bottom: 2rem;"></div>

<div style="margin-bottom: 2rem;"></div>



### Dr. SOPHIA VOURLI

*Senior Researcher in the Institute of Biosciences and Applications at NCSR "Demokritos"* 

Dr. S. Vourli is a Biologist. Her research focuses on microbiology and pharmacology, with expertise in antimicrobial resistance, particularly in Gram-negative bacteria and mechanisms of resistance to last-resort antibiotics. She has contributed to studies on molecular diagnostics for infections.

*e-mail:* [vourli@bio.demokritos.gr](mailto:vourli@bio.demokritos.gr?subject=BioSUPERCAP%20Inquiry)

<div style="margin-bottom: 2rem;"></div>

<div style="margin-bottom: 2rem;"></div>



### Dr. IOANNIS KARAYIANNIS

*Research Scientist at Hellenic Pasteur Institute*

Dr. I. Karayiannis is a Biologist. His research is focused on bacterial molecular pathogenesis utilizing in vitro and in vivo infection systems in the Helicobacter pylori (H. pylori) model for infection; genetic manipulation of bacterial and mammalian; bacterial-host interactions at genetic and protein level.

*e-mail:* [jkaragiannis@pasteur.gr](mailto:jkaragiannis@pasteur.gr?subject=BioSUPERCAP%20Inquiry)

<div style="margin-bottom: 2rem;"></div>

<div style="margin-bottom: 2rem;"></div>



### M.Sc. ALEXANDROS SAKELLARIS

*Research Associate at the Institute of Nanoscience and Nanotechnologies, NCSR "Demokritos"*

M.Sc. A. Sakellaris is a Plant scientist. His research interests are in the field of biofilm physiology, antibiotic resistance and microbial biotechnology and more specifically in the development and investigation of poly-microbial biofilms. 

*e-mail:* [a.sakellaris@inn.demokritos.gr](mailto:a.sakellaris@inn.demokritos.gr?subject=BioSUPERCAP%20Inquiry)

<div style="margin-bottom: 2rem;"></div>

<div style="margin-bottom: 2rem;"></div>

